### ISSUE TITLE
Not importing in python3

### ISSUE THREAD

**Issue by droidzone** [lebedov/python-pdfbox#1]
`import pdfbox
p = pdfbox.PDFBox()
text = p.extract_text('/home/joel/sc.pdf')
print(text)`

Error:
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/joel/scripts/pdfbox.py", line 2, in <module>
    p = pdfbox.PDFBox()
AttributeError: module 'pdfbox' has no attribute 'PDFBox'
`

**Comment by lebedov** [comment]
I cannot replicate this error with Python 3.6.5. What version of Python and of python-pdfbox are you using? How did you install the package?

**Comment by lebedov** [comment]
Closing - feel free to reopen if you have further info.
