### ISSUE TITLE
extract_text returns None

### ISSUE THREAD

**Issue by ecatkins** [lebedov/python-pdfbox#13]
```
OS: MacOS Mojave
Python: 3.7.4
PDFBox: 2.0.16
python-pdfbox: 0.1.7
```

After upgrading from 0.1.6 -> 0.1.7, when I run `extract_text` method as below, it returns `None` whereas previously returning the correct text.

```
import pdfbox
p = pdfbox.PDFBox()
text = p.extract_text('/path/to/my_file.pdf')
```

**Comment by jgiere** [comment]
OS: Ubuntu 18.04
Python: 3.6.8
PDFBox: 2.0.16
python-pdfbox: 0.1.7 

I can confirm this behaviour on my environment as well.

**Comment by kuraga** [comment]
@lebedov , confirm.

**Comment by lebedov** [comment]
Confirmed. The wrappers now conform more closely to the wrapped tool's interface and only write to output files.

**Comment by ecatkins** [comment]
@lebedov So the usage needs to be changed in the README, yes?

**Comment by lebedov** [comment]
@ecatkins Yes - fixed.
