### ISSUE TITLE
Version of .jar file change to 2.0.11

### ISSUE THREAD

**Issue by CaioCris** [lebedov/python-pdfbox#2]
Hi there! 

I had an issue because of the .jar file version, I check in the GitHub is the 2.0.10, but in the PDFBox website is already 2.0.11, so if the version is different when the python-pdfbox/pdfbox/__init__.py
try the download, they got a 404 Not Found. 

I would suggest you use an HTML handler lib, like bs4 or xpath, may this help you to do something more generic with the .jar files sources.

**Comment by lebedov** [comment]
Updated to automatically figure out and download the latest version.
