### ISSUE TITLE
[Errno 2] No such file or directory: '/usr/lib/jvm'

### ISSUE THREAD

**Issue by ZF1546** [lebedov/python-pdfbox#22]
FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/jvm'

**Comment by lebedov** [comment]
Can you please provide more information and paste the full traceback for the exception? What version of python-pdfbox are you using? Do you have Java installed?

**Comment by ZF1546** [comment]
I'm so sorry to have sent a message for so long, The problem has been solved.
I hadn't install Java.
Thanks very much.

**Comment by lebedov** [comment]
No problem.
