### ISSUE TITLE
-force argument is causing malformed command

### ISSUE THREAD

**Issue by seanlaw** [lebedov/python-pdfbox#3]
I haven't dug into this from the code but it looks like

    p.extract('file.pdf', force=True)

Causes:

    Exception in thread "main" java.io.FileNotFoundException: -force (No such file or directory)

Running the above command without `force=True` produces the expected output

**Comment by lebedov** [comment]
The -force option doesn't appear to be supported anymore; I just removed it (and reported the incorrect online docs to the pdfbox folks).
