### ISSUE TITLE
Can we get font name and size of the text from pfg?

### ISSUE THREAD

**Issue by jigsawcoder** [lebedov/python-pdfbox#30]
I want to know how to get the fontname and size of the text extracted from pdf using pdbox python? If yes, how?

Thanks

**Comment by lebedov** [comment]
From what I can tell, this info is not accessible via the pdfbox command-line interface wrapped by python-pdfbox; you will have to wrap the [relevant part of the Java API](https://pdfbox.apache.org/docs/2.0.13/javadocs/org/apache/pdfbox/pdmodel/PDResources.html#getFontNames--) yourself if you want to access it from Python - see [this gist](https://gist.github.com/lebedov/cefbec588c2b2bd0251ba505bd8bf933) for an example of how to do so. [This post](https://stackoverflow.com/questions/38369096/how-to-extract-fonts-from-pddocument-in-pdfbox-2-0-2) may also be helpful.
